#!/bin/sh

host=www.macrelix.org

export RELIX_URL=http://$host/pub/experimental/

test -n "$1" && export RELIX_PLATFORM="$1"

export MBIN=mBin

echo Checking $host for latest version...

htget $RELIX_URL | perl -we 'my $pf = $ENV{RELIX_PLATFORM} || substr( `cat /etc/platform`, 0, -1 ); while (<>) { m{ ( relix-${pf}_[\d-]+ ) \.gz }osx and $last = $1; }; exec "/etc/bootstrap/upgrade-lamp", $last;'

