#!/bin/sh

host=www.macrelix.org

export RELIX_URL=http://$host/pub/experimental/

test -n "$1" && export RELIX_PLATFORM="$1"

export MBIN=mBin

echo Checking $host for latest version...

htget http://$host > /dev/null 2>&1 || failed=1

test -n $failed && echo "upgrade: can't reach $host" >&2
test -n $failed && exit 1

htget $RELIX_URL | perl -we 'my $pf = $ENV{RELIX_PLATFORM} || substr( `cat /etc/platform`, 0, -1 ); while (<>) { m{ ( relix-${pf}_[\d-]+ ) \.gz }osx and $last = $1; }; exec "/etc/bootstrap/upgrade-lamp", $last;'

