#!/usr/bin/perl

# Our custom MacRelix runtime has no perl library
#use warnings;
#use strict;


sub spew
{
	my ( $path, $data ) = @_;
	
	open my $out, ">", $path or die "$path: $!\n";
	
	print $out $data or die "$path: $!\n";
	
	close $out or die "$path: $!\n";
}

sub set_button_title
{
	my ( $title ) = @_;
	
	spew( "v/button/v/v/title", "$title\n" );
}

sub set_checksum_text
{
	my ( $text ) = @_;
	
	spew( "v/checksum/v/v/text", $text );
}

sub wait_for_button
{
	open my $in, "<", "v/button/v/v/socket" or die;
	
	sysread $in, my( $buffer ), 1 or die;
}

my $progress = q|perl -pe 'm{^ \s* (\d+) \s* / \s* (\d+) \s* $}x and $_ = ($1/$2 * 10000) . "\n"'|;

if ( -f "/sys/mac/rom" )
{
	#set_button_title( "Check" );  # already set in init
	
	wait_for_button();
	
	my $checksum = `/usr/bin/rom-checksum /sys/mac/rom`;
	
	chop $checksum;
	
	set_checksum_text( $checksum );
	
	if ( my $valid = $checksum =~ m{^ [0-9A-Fa-f]{8} $}x )
	{
		my $file = "/$checksum.rom";
		
		set_button_title( "Copy" );
		
	click:
		
		wait_for_button();
		
		system( "/sys/kernel/bin/beep" ), goto click if -e $file;
		
		set_button_title( "Wait" );
		
		link "/gui/new/progress", "v/progress/v/view";
		
		system "/usr/bin/copy --dump-progress /sys/mac/rom $file | $progress > v/progress/v/v/value";
		system "/bin/sync";
		
		unlink "v/progress/v/view";
		
		my $new_checksum = `/usr/bin/rom-checksum $file`;
		
		#chop $new_checksum;
		
		set_checksum_text( $new_checksum );
	}
}
else
{
	set_checksum_text( "ROM not found" );
}

set_button_title( "Quit" );

wait_for_button();

system( "/sys/kernel/bin/quit" );
