#!/bin/sh

set -e

dest="/sys/app/dir/../$1"

test -d $dest && echo You already have $1. && exit || true

cd /tmp

echo Downloading $1.gz...
htget --dump-progress -O $RELIX_URL/$1.gz | progress Downloading

echo Checking signature...
key=46e70108538e13868fc8d8454610d47e9ca09d934aa2224af806547190aa7a93
arcsign unseal -K $key $1.gz

echo Decompressing...
gzip -d --name $1.gz

echo Decoding archive...
macbin decode $1.$MBIN

mv $1 $dest

rm "$1.$MBIN"

sync

echo Done.

