#!/bin/sh

set -e

A-line -B Genie tools tests git
A-line -C Genie tools tests git
A-line -B56 Genie
A-line -B46 tools tests git
A-line -RB Genie tools tests git
A-line -RC Genie tools tests git
A-line -RB56 Genie
A-line -RB46 tools tests git
