#!/bin/sh

set -e

archive="archive.pl"

date '+export BUILD_DATE="%Y-%m-%d %H:%M"' > /tmp/set-lamp_build_date

. /tmp/set-lamp_build_date

perl $archive 68k
perl $archive 68k~

perl $archive os9
perl $archive os9~

perl $archive osx
perl $archive osx~

