#!/bin/sh

cd /gui/port/about

/usr/bin/touch window/select 2> /dev/null  &&  exit  ||  /bin/true

exec 0>&2             # save fd 2
exec 2> /dev/null     # discard stderr
exec 9> lock || exit  # bail if the lock is taken
exec 2>&0             # restore fd 2
exec 0< /dev/null     # clear fd 0

iconid=128

echo 0 > vis
echo 220,68 > size
echo About MacRelix > title

echo > procid 4

/usr/bin/touch window

echo 0 > window/text-font

/bin/ln /gui/new/stack view

icon=view/icon/v
main=view/main/v

/bin/ln /gui/new/frame $icon

echo 32 > $icon/width
echo 32 > $icon/height
echo 13 > $icon/.margin-top
echo 23 > $icon/.margin-left
echo 23 > $icon/.margin-right

/bin/ln /gui/new/icon $icon/v

echo $iconid > $icon/v/data

/bin/ln /gui/new/frame $main

echo 13 > $main/.margin-top
echo 13 > $main/.margin-right
echo 78 > $main/.margin-left

/bin/ln /gui/new/caption $main/v

echo >> $main/v/text "MacRelix"
echo >> $main/v/text "by Josh Juran"

echo 1 > $icon/v/disabling
echo 1 > $main/v/disabling

/usr/bin/daemonize --cwd --ctty=tty -- /usr/bin/idle

echo 1 > vis

