#!/bin/sh

host=www.macrelix.org/pub

test -z "$RELIX_SITE" && RELIX_SITE="$host"

export RELIX_SITE

list=http://$RELIX_SITE/experimental/

test -n "$1" && export RELIX_PLATFORM="$1"

export MBIN=mBin

echo Checking $RELIX_SITE for latest version...

htget $list | perl -we 'my $pf = $ENV{RELIX_PLATFORM} || substr( `cat /etc/platform`, 0, -1 ); while (<>) { m{ ( relix-${pf}_[\d-]+ ) \.gz }osx and $last = $1; }; exec "/etc/bootstrap/upgrade-lamp", $last;'

