#!/bin/sh

cd /new/port

echo Diagnostics > title

echo 700x400 > size
echo 10,50 > pos

touch window

echo 4 > window/text-font
echo 9 > window/text-size

ln /new/scrollframe  view
ln /new/frame        view/v
ln /new/console      view/v/v

ln -s v/v view/target

echo 1 > view/vertical
echo 4 > view/v/padding

mv view/v/v/tty tty

daemonize --cwd --ctty=tty chain cat "$1" ';' idle

