product app
creator 'Vrtc'

use CGQuickDraw
use MacPlus
use Pedestal
use null-console
use worldview

frameworks Carbon

rez icons.r
rez vers.r

rez Pedestal:0080-Apple.MENU.r
rez Pedestal:Pedestal.aete.r
rez Pedestal:Pedestal.menu.r
rez Pedestal:Pedestal.size.r
