#!/bin/sh

AppName="$1"

if [ -z "$AppName" ]; then
	AppName=TestApp
fi

mkdir -p ~/var/run/raster

SCREEN=~/var/run/raster/ams
RASTER="--raster=$SCREEN"
FIFO="$SCREEN.fifo"

test -e $FIFO  ||  mkfifo $FIFO
chmod 0622 $FIFO

CORE=ams-core
RSRC=ams-rsrc
UI=ams-ui

test -f $SCREEN || raster make -g 512x342*1 -m paint -R $SCREEN
raster init $SCREEN

interact $RASTER -t "Advanced Mac Substitute" | \
graft 8<&0 \
	freemountd -q --root ~/68k // \
	xv68k $RASTER -m [ $CORE --events-fd=8 ] -m $RSRC -m $UI ~/68k/app $AppName
