#!/bin/sh

cd /gui/new/port

echo 512x342 > size

ln new/stack view

ln new/eventtap v/events/view
ln new/bitmap   v/screen/view

events=v/events/v/stream
screen=v/screen/v/bits

echo 4 > procid

touch window

perl -e 'sleep 0 while !-f "v/screen/v/bits"'

CTTY=--ctty=tty
SCREEN=--screen=$screen
EVENTS=--events-fd=8

FS=$HOME/68k
APP=$FS/app
App=TestApp

daemonize --cwd $CTTY -- graft freemountd --root $FS // xv68k $SCREEN -m [ macos $EVENTS ] -m macrsrc $APP $App 8< $events
