#!/bin/sh

cd /gui/new/port

echo 512x342 > size

ln new/stack view

ln new/eventtap v/events/view
ln new/bitmap   v/screen/view

echo 512x342 > v/screen/v/size

events=v/events/v/stream
screen=v/screen/v/bits

echo 4 > procid

touch window

CTTY=--ctty=tty
SCREEN=--screen=$screen
EVENTS=--events-fd=8

FS=$HOME/68k
APP=$FS/app
App=TestApp

CORE=ams-core
RSRC=ams-rsrc

daemonize --cwd $CTTY -- graft freemountd --root $FS // xv68k $SCREEN -m [ $CORE $EVENTS ] -m $RSRC $APP $App 8< $events
