#!/bin/sh

echo "Downloading /usr/lib/perl archive..."
htget http://lamp.sourceforge.net/experimental/usr-lib-perl.jbin.gz --save /tmp/usr-lib-perl.jbin.gz

echo "Decompressing archive..."
gzip -d /tmp/usr-lib-perl.jbin.gz

echo "Decoding archive..."
macbin --decode /tmp/usr-lib-perl.jbin /usr/lib/

echo "Done."

