#!/bin/sh

set -e

cd /tmp

experimental="http://lamp.sourceforge.net/experimental/"

archive=usr-lib-perl.mBin
gzarchive=$archive.gz

url=$experimental$gzarchive

echo "-> htget -O $url"
htget -O $url

echo "-> gzip -d $gzarchive"
gzip -d $gzarchive

echo "-> macbin --decode $archive /usr/lib/"
macbin --decode $archive /usr/lib/

