#!/bin/sh

list=http://lamp.sourceforge.net/experimental/

echo Checking lamp.sourceforge.net for latest version...

htget $list | grep lamp-std | perl -we 'while (<>) { $last = $_; }; $last =~ s{^ .* (lamp-std_[\d-]+) .mbin.gz .* $}{$1}xs; exec "/etc/bootstrap/upgrade-lamp", $last;'

