#!/bin/sh

test -d $HOME/$1 && echo You already have $1. && exit

cd /tmp

echo Downloading $1.bin+.gz...
htget --save http://lamp.sourceforge.net/experimental/$1.bin+.gz

echo Decompressing...
gzip -d $1.bin+.gz

echo Decoding archive...
macbin --decode $1.bin+

mv $1 $HOME/$1

echo Done.

