#!/bin/sh

host=lamp.sourceforge.net

list=http://$host/experimental/

export MBIN=jbin

echo Checking $host for latest version...

htget $list | grep "lamp-std_[0-9-]+\\.$MBIN.gz" | perl -we 'while (<>) { $last = $_; }; $last =~ s{^ .* (lamp-std_[\d-]+) \.$ENV{MBIN}\.gz .* $}{$1}oxs; exec "/etc/bootstrap/upgrade-lamp", $last;'

