#!/bin/sh

set -e

dest="/sys/app/dir/../$1"

test -d $dest && echo You already have $1. && exit || true

cd /tmp

echo Downloading $1.gz...
htget --dump-progress -O http://$RELIX_SITE/experimental/$1.gz | progress Downloading

echo Decompressing...
gzip -d --name $1.gz

echo Decoding archive...
macbin --decode $1.$MBIN

mv $1 $dest

rm "$1.$MBIN"

echo Done.

