#!/bin/sh

set -e

test -n "$HOME" || echo "$0: HOME is not set"
test -n "$HOME" || exit 1

test -d $HOME || echo "$0: HOME doesn't exist"
test -d $HOME || exit 1

dest="/sys/app/dir/../$1"

test -d $dest && echo You already have $1. && exit || true

cd /tmp

echo Downloading $1.gz...
htget -O http://$RELIX_SITE/experimental/$1.gz

echo Decompressing...
gzip -d --name $1.gz

echo Decoding archive...
macbin --decode $1.$MBIN

mv $1 $dest

echo Done.

