#!/bin/sh

echo > v/v/text "???"

sleep 2

echo > v/v/text "Here's a simple demo:"

sleep 2

echo >> v/v/text
echo >> v/v/text "\$ cd \$FORGE/gui/port/hello"

sleep 1.5

echo >> v/v/text "\$ exec 9> lock"

sleep 1.5

echo >> v/v/text "\$ ln new/caption view"

sleep 1.5

echo >> v/v/text "\$ touch window"

sleep 1.5

echo >> v/v/text "\$ echo Hello > v/text"

