#!/bin/sh

echo > v/v/text "Now let's try it for real."

sleep 2

echo 10,50 > pos

sleep 1

echo 800x400 > size

sleep 1

rm /tmp/demo-console 2>/dev/null

/bin/teletype /bin/sh -c '/bin/ln -s $WINDOW /tmp/demo-console; /bin/login'

sleep 1

echo 10,484 > /tmp/demo-console/pos

CONSOLE=/tmp/demo-console/v/v/v

sleep 2

echo >> v/v/text
echo >> v/v/text "That's a live console --"

sleep 1

echo >> v/v/text "text written to it will execute."

sleep 3.5

echo > v/v/text "\$ cd /gui/new/port"

sleep 1

echo >> $CONSOLE/text "cd /gui/new/port"

sleep 1.5

echo >> v/v/text "\$ ln /gui/new/caption view"

sleep 1

echo >> $CONSOLE/text "ln /gui/new/caption view"

sleep 1.5

echo >> v/v/text "\$ touch window"

sleep 1

echo >> $CONSOLE/text "touch window"

sleep 2

echo >> v/v/text "\$ echo Hello > v/text"

sleep 1

echo >> $CONSOLE/text "echo Hello > v/text"

