#!/bin/sh

CONSOLE=/tmp/demo-console/v/v/v

echo > v/v/text "Let's tweak a few things:"

sleep 2

echo >> v/v/text
echo >> v/v/text "\$ echo 550,500 > pos"

sleep 1

echo >> $CONSOLE/text "echo 550,500 > pos"

sleep 1.5

echo >> v/v/text "\$ echo 448x240 > size"

sleep 1

echo >> $CONSOLE/text "echo 448x240 > size"

sleep 1.5

perl >> v/v/text -e 'print "The font... "'

sleep 1

echo >> $CONSOLE/text "echo 72 > w/text-size"

sleep 1

echo >> $CONSOLE/text "echo 0 > w/text-font"

sleep .5

perl >> v/v/text -e 'print "no wait...  "'

sleep 1

echo >> $CONSOLE/text "echo 2 > w/text-font"

sleep 1

echo >> v/v/text "And..."

sleep 1

echo 900x400 > size

sleep 1

echo >> v/v/text "\$ echo Hello world > v/text"

sleep 1

echo >> $CONSOLE/text "echo Hello world > v/text"

sleep 3

echo >> $CONSOLE/text "echo 'Hello, world. :-)' > title"

sleep 2

echo >> $CONSOLE/text "echo '*applause*' >> v/text"

