#!/bin/sh

echo 10,50 > $WINDOW/pos

echo 800x600 > size

echo FORGE > title

touch window

echo 48 > w/text-size
echo  4 > w/text-font

/bin/ln /gui/new/frame   view
/bin/ln /gui/new/caption view/v

echo 4 > view/padding

